/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;

import java.awt.BorderLayout;
import java.sql.Connection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
import tools.HibernateUtil;

/**
 * Deklarasi kelas ReportView
 * @author USER
 */
public class ReportView extends javax.swing.JInternalFrame {

    private SessionFactory sf;
    /**
     * Method konstruktor
     * @param sessionFactory tipe data SessionFactory
     * @param url tipe data string
     */
    public ReportView(SessionFactory sessionFactory, String url) {
        initComponents();
        this.sf = HibernateUtil.getSessionFactory();
        Connection connection = null;
        try {
            connection = sf.getSessionFactoryOptions().getServiceRegistry().
                    getService(ConnectionProvider.class).getConnection();
            JasperDesign jd = JRXmlLoader.load(url);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jPrint = JasperFillManager.fillReport(jr, null, connection);
            JRViewer viewer = new JRViewer(jPrint);
            panelReportView.setLayout(new BorderLayout());
            panelReportView.add(viewer);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReportView = new javax.swing.JPanel();

        javax.swing.GroupLayout panelReportViewLayout = new javax.swing.GroupLayout(panelReportView);
        panelReportView.setLayout(panelReportViewLayout);
        panelReportViewLayout.setHorizontalGroup(
            panelReportViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        panelReportViewLayout.setVerticalGroup(
            panelReportViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReportView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReportView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelReportView;
    // End of variables declaration//GEN-END:variables
}
