/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.EmployeeController;
import viewemp.EmployeeView;
import controllers.TempControllers;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Employee;
import models.EmployeeTemp;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import viewemp.EmployeeViewH;

/**
 * Deklarasi kelas HrView
 * @author Nande
 */
public class HrView extends javax.swing.JInternalFrame {

    private SessionFactory sessionFactory;
    private final TempControllers tempController;
    private Employee employee;
    private EmployeeController employeeController;

    /**
     * Method konstruktor
     * @param sessionFactory tipe data SessionFactory
     * @param employee tipe data Employee
     */
    public HrView(SessionFactory sessionFactory, Employee employee) {
        initComponents();
        tempController = new TempControllers(sessionFactory);
        this.sessionFactory = sessionFactory;
        bindingData(tempController.getAll());
        this.employee = employee;
        employeeController = new EmployeeController(sessionFactory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployeeTemp = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSettingProfile = new javax.swing.JMenu();
        menuNewEmployee = new javax.swing.JMenu();
        menuSite = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setMaximizable(true);
        setTitle("HUMAN RESOURCE VIEW");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblEmployeeTemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEmployeeTemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeTempMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployeeTemp);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("REQUEST TABLE");

        menuSettingProfile.setText("SETTING PROFILE");
        menuSettingProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSettingProfileMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSettingProfile);

        menuNewEmployee.setText("NEW EMPLOYEE");
        menuNewEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNewEmployeeMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuNewEmployee);

        menuSite.setText("SITE");
        menuSite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSiteMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSite);

        menuLogout.setForeground(new java.awt.Color(255, 0, 0));
        menuLogout.setText("LOG OUT");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap(363, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed
    /**
     * Method untuk melakukan logout dan memanggil kelas login
     * @param evt merupakan sebuah event
     */
    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        // TODO add your handling code here:
        Login login = new Login(sessionFactory);
        this.getParent().add(login);
        login.setLocation(480, 200);
        login.setVisible(true);

        dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked
    /**
     * Method untuk memanggil kelas SiteView
     * @param evt merupakan sebuah event
     */
    private void menuSiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiteMouseClicked
        // TODO add your handling code here:
        SiteView siteView = new SiteView(sessionFactory);
        this.getParent().add(siteView);
        siteView.setVisible(true);

    }//GEN-LAST:event_menuSiteMouseClicked
    /**
     * Method untuk memnaggil kelas EmployeeViewH
     * @param evt merupakan sebuah event
     */
    private void menuSettingProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSettingProfileMouseClicked
        // TODO add your handling code here:
        EmployeeViewH employeeView = new EmployeeViewH(sessionFactory, employee, employee,  1);
        this.getParent().add(employeeView);
        employeeView.setVisible(true);
    }//GEN-LAST:event_menuSettingProfileMouseClicked
    /**
     * Method agar dapat menekan salah satu data pada table
     * @param evt merupakan sebuah event
     */
    private void tblEmployeeTempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeTempMouseClicked
        // TODO add your handling code here:
        EmployeeViewH employeeViewH = new EmployeeViewH(sessionFactory, setEmployee(), employee, 0);
        this.getParent().add(employeeViewH);
        employeeViewH.setVisible(true);
    }//GEN-LAST:event_tblEmployeeTempMouseClicked
    /**
     * Method untuk memanggil kelas dari EmployeeViewH
     * @param evt merupakan sebuah event
     */
    private void menuNewEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNewEmployeeMouseClicked
        // TODO add your handling code here:
        EmployeeViewH employeeView = new EmployeeViewH(sessionFactory, new Employee(), employee, 1);
        this.getParent().add(employeeView);
        employeeView.setVisible(true);
    }//GEN-LAST:event_menuNewEmployeeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuNewEmployee;
    private javax.swing.JMenu menuSettingProfile;
    private javax.swing.JMenu menuSite;
    private javax.swing.JTable tblEmployeeTemp;
    // End of variables declaration//GEN-END:variables
    /**
     * Method untuk menampilkan data dari Employee temporary
     * @param empTemp dengan tipe data List
     */
    private void bindingData(List<Object> empTemp) {
        String[] header = {"No", "REQUEST ID", "EMPLOYEE ID", "EMAIL", "PHONE", "NPWP", "SKCK", "BPJS"};
        String[][] data = new String[empTemp.size()][header.length];
        int i = 0;
        for (Object object : empTemp) {
            EmployeeTemp eTemp = (EmployeeTemp) object;
            data[i][0] = (i + 1) + "";
            data[i][1] = eTemp.getTempId() + "";
            data[i][2] = eTemp.getEmployeeId().getEmployeeId() + "";
            data[i][3] = eTemp.getEmail() + "";
            data[i][4] = eTemp.getPhone() + "";
            data[i][5] = eTemp.getNpwp() + "";
            data[i][6] = eTemp.getSkck() + "";
            data[i][7] = eTemp.getBpjs() + "";
            i++;
        }
        tblEmployeeTemp.setModel(new DefaultTableModel(data, header));

    }
    
    private Employee setEmployee(){
        Employee e = new Employee();
        int row = tblEmployeeTemp.getSelectedRow();
        e.setEmployeeId(new Long(tblEmployeeTemp.getValueAt(row, 2) + ""));
        e = (Employee) employeeController.getById(e.getEmployeeId()+"");
        e.setEmail(tblEmployeeTemp.getValueAt(row, 3)+"");
        e.setPhone(tblEmployeeTemp.getValueAt(row, 4)+"");
        e.setNpwp(tblEmployeeTemp.getValueAt(row, 5)+"");
        e.setSkck(tblEmployeeTemp.getValueAt(row, 6)+"");
        e.setBpjs(tblEmployeeTemp.getValueAt(row, 7)+"");
        return e;
    }
}
