/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.EmployeeController;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Employee;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import report.ReportView;
import tools.HibernateUtil;
import viewemp.EmployeeViewM;

/**
 * Dekalrasi kelas ManagerView
 * @author Nande
 */
public class ManagerView extends javax.swing.JInternalFrame {

    private SessionFactory sessionFactory;
    private Employee employee;
    private EmployeeController employeeController;
    /**
     * Method konstruktor
     * @param sessionFactory tipe data SessionFactory
     * @param employee tipe data Employee
     */
    public ManagerView(SessionFactory sessionFactory, Employee employee) {
        initComponents();
        this.employee = employee;
        employeeController = new EmployeeController(HibernateUtil.getSessionFactory());
        bindingData(employeeController.getByManagerId(employee));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblEmployeeId = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSetting = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setMaximizable(true);
        setTitle("MANAGER VIEW");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Employees", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEmployee);

        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrint)
                        .addGap(350, 350, 350)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Employee ID :");

        lblEmployeeId.setText("18001");

        menuSetting.setText("SETTING PROFILE");
        menuSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSettingMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSetting);

        menuLogout.setForeground(new java.awt.Color(255, 0, 0));
        menuLogout.setText("LOG OUT");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmployeeId)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeId)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Method untuk logout/keluar dari sistem
     * @param evt merupakan sebuah event
     */
    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        // TODO add your handling code here:
        Login login = new Login(sessionFactory);
        this.getParent().add(login);
        login.setLocation(480, 200);
        login.setVisible(true);

        dispose();

    }//GEN-LAST:event_menuLogoutMouseClicked
    /**
     * Method untuk memanggil kelas EmployeeViewM 
     * @param evt merupakan sebuah event
     */
    private void menuSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSettingMouseClicked
        // TODO add your handling code here:
        EmployeeViewM employeeViewM = new EmployeeViewM(sessionFactory, employee);
        this.getParent().add(employeeViewM);
        employeeViewM.setVisible(true);
    }//GEN-LAST:event_menuSettingMouseClicked
    /**
     * Method untuk mencetak list employee report dan memanggil kelas ReportView
     * @param evt merupakan sebuah event
     */
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        HashMap parameter = new HashMap();
        parameter.put("listReport", lblEmployeeId.getText());
        ReportView reportView = new ReportView(sessionFactory, "src\\report\\EmployeeListReport.jrxml");
        this.getParent().add(reportView);
        reportView.setLocation(480, 200);
        reportView.setVisible(true);
        
    }//GEN-LAST:event_btnPrintActionPerformed
    /**
     * Method untuk menampilkan list data employee
     * @param emmployee dengan tipe data List
     */
    private void bindingData(List<Employee> emmployee){
    String[] header = {"No", "EMPLOYEE ID", "FIRST NAME", "LAST NAME", "EMAIL", "SALARY", "PHONE", "SITE NAME", "HIRE DATE"};
        String[][] data = new String[emmployee.size()][header.length];
        int i = 0;
        for (Object object : emmployee) {
            Employee e = (Employee) object;
            data[i][0] = (i + 1) + "";
            data[i][1] = e.getEmployeeId()+ "";
            data[i][2] = e.getFirstName();
            data[i][3] = e.getLastName();
            data[i][4] = e.getEmail();
            data[i][5] = e.getSalary()+"";
            data[i][6] = e.getPhone();
            String site = "null";
            if(e.getSiteId() != null) site = e.getSiteId().getSiteName();
            data[i][7] = site;
            data[i][8] = e.getHireDate().toString();
            i++;
        }
        tblEmployee.setModel(new DefaultTableModel(data, header));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmployeeId;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuSetting;
    private javax.swing.JTable tblEmployee;
    // End of variables declaration//GEN-END:variables
}
